// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "shipping-management/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// GetPackageUseCase is an autogenerated mock type for the GetPackageUseCase type
type GetPackageUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, uuid
func (_m *GetPackageUseCase) Execute(ctx context.Context, uuid string) (entities.Package, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 entities.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Package, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Package); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(entities.Package)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetPackageUseCase creates a new instance of GetPackageUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetPackageUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetPackageUseCase {
	mock := &GetPackageUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
