// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "shipping-management/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// HireCarrierForPackageDeliveryUseCase is an autogenerated mock type for the HireCarrierForPackageDeliveryUseCase type
type HireCarrierForPackageDeliveryUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, packageUuid, carrierUuid
func (_m *HireCarrierForPackageDeliveryUseCase) Execute(ctx context.Context, packageUuid string, carrierUuid string) (entities.Package, error) {
	ret := _m.Called(ctx, packageUuid, carrierUuid)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 entities.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (entities.Package, error)); ok {
		return rf(ctx, packageUuid, carrierUuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) entities.Package); ok {
		r0 = rf(ctx, packageUuid, carrierUuid)
	} else {
		r0 = ret.Get(0).(entities.Package)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, packageUuid, carrierUuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHireCarrierForPackageDeliveryUseCase creates a new instance of HireCarrierForPackageDeliveryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHireCarrierForPackageDeliveryUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *HireCarrierForPackageDeliveryUseCase {
	mock := &HireCarrierForPackageDeliveryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
