// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "shipping-management/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// PackageQuotationUseCase is an autogenerated mock type for the PackageQuotationUseCase type
type PackageQuotationUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, packageUuid
func (_m *PackageQuotationUseCase) Execute(ctx context.Context, packageUuid string) ([]entities.Quotation, error) {
	ret := _m.Called(ctx, packageUuid)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []entities.Quotation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entities.Quotation, error)); ok {
		return rf(ctx, packageUuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.Quotation); ok {
		r0 = rf(ctx, packageUuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Quotation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, packageUuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPackageQuotationUseCase creates a new instance of PackageQuotationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPackageQuotationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PackageQuotationUseCase {
	mock := &PackageQuotationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
